version: '3'

services:

  app:
    build: 
      context: ./App
      dockerfile: Dockerfile.react
    networks:
      - frontend
    ports:
      - "3001:3000"
    depends_on:
      - server
      - db
    restart: on-failure

  server:
    build: 
      context: ./Server
      dockerfile: Dockerfile.express
    networks:
      - backend
      - frontend
    ports:
      - "4444:4444"
    depends_on: 
      - db
    restart: on-failure

  db:
    build: 
      context: ./Database
      dockerfile: Dockerfile.mongo
    networks:
      - backend
    ports:
      - "27027:27017" 
    restart: on-failure

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge